### ISSUE TITLE
optional `publicPath` is used in the src filename when loading polyFilly

### ISSUE THREAD

**Issue by boudewijn-zicht** [SebastianS90/webpack-polyfill-injector#11]
This causes the src filename to start with `undefined`, resulting in an invalid filename, i.e. `o.src="undefinedjs/polyfills.min.js"`

I've solved this by adding the missing `publicPath` into the webpack config like so:
```
{
   output: {
      publicPath: ''
   }
}
```

However, it would be nicer if this could be fixed in PluginState.js by giving it a default value, i.e:
`this.publicPath = compilation.options.output.publicPath;` -> `this.publicPath = (undefined == compilation.options.output.publicPath ? '' : compilation.options.output.publicPath);`

If the author agrees I'll make an appropriate PR.

**Comment by SebastianS90** [comment]
> If the author agrees I'll make an appropriate PR.

yes, please post a PR for it
