### ISSUE TITLE
UglifyJS break Function.name test by default settings. 

### ISSUE THREAD

**Issue by Taraflex** [SebastianS90/webpack-polyfill-injector#21]
Function.name test after UglifyJS equal 
```
"x" === function() {}.name
```
Better alternative
```js
window.open.name === 'open'
```

**Comment by SebastianS90** [comment]
Nothing I can fix in this plugin, please consider sending a PR to change it [in `polyfill-library`](https://github.com/Financial-Times/polyfill-library/blob/master/polyfills/Function/name/detect.js).
