### ISSUE TITLE
PolyFillLibrary is not a constructor

### ISSUE THREAD

**Issue by KevinGruber** [SebastianS90/webpack-polyfill-injector#26]
Hi I used your Loader and Plugin and it dies with PolyFillLibrary is not a constructor.
when I log PolyFillLibrary it is a plain Object and not a constructor.

I don't know if it was a change in PolyFillLibrary or something else.
Would be awesome if somebody could give me a hint why it is behaving like that.

Found out they changed in a Patch Version from constructor to Object.
Change happened from 3.27.1 to 3.27.2.

BR,
Kev

https://github.com/SebastianS90/webpack-polyfill-injector/blob/5c73afa544abde2037f59069d28b3cfc4f387691/src/PluginState.js#L13

**Comment by terion-name** [comment]
Changing API in a patch version 🤦

**Comment by SebastianS90** [comment]
Thanks for the info, I'll update my package tonight to work around the bc breaking change in `polyfill-library`.

**Comment by SebastianS90** [comment]
Fixed and released as `v3.0.2`. Does it work for you?

**Comment by KevinGruber** [comment]
Yes thanks runs through now.
