### ISSUE TITLE
How to remove "use strict" to support ie11

### ISSUE THREAD

**Issue by ProperSag** [SebastianS90/webpack-polyfill-injector#27]
Hi, is it possible to remove "use strict" from the js bundle
I am using external libraries which use "use strict"
And im getting Syntax error in IE11

**Comment by ProperSag** [comment]
update:
i tried using
remove-strict-webpack-plugin
removing all the "use strict"
but now im getting error for this code:
```

/***/ (function(module, exports, __webpack_require__) {

;
```

**Comment by SebastianS90** [comment]
I guess I cannot do anything within my package, as it depends on the polyfill sources from `polyfill-library`. For example, [see what their service provides as `Promise` polyfill for IE11](https://polyfill.io/v2/polyfill.js?flags=&features=Promise&ua=Mozilla/5.0%20(Windows%20NT%206.3;%20Trident/7.0;%20rv:11.0)%20like%20Gecko). The code contains `"use strict";`

**Comment by SebastianS90** [comment]
Do you have an example configuration where you get an error because of `use strict`?

**Comment by ProperSag** [comment]
I guess i had a misunderstanding
I need to change the bundle
Not just add missing lib's
I end up using babel polyfill, setting in the config IE11 and that worked
