### ISSUE TITLE
Does not seem to skip css files

### ISSUE THREAD

**Issue by andyo729** [SebastianS90/webpack-polyfill-injector#3]
Something about this script is crashing on any `import '*.css'`. I haven't tracked down the exact issue, but I get an error on `text.forEach is undefined` for each one of those files.

**Comment by andyo729** [comment]
This looks like it had something to do with the `extract-text-plugin` integration. I will dig around some more before closing this out, but I don't think it's your issue.

**Comment by Francismb** [comment]
@AO16 Did you find a fix? I too am running into this issue.

**Comment by SebastianS90** [comment]
Using the `this-compilation` instead of the `compilation` hook for the compiler should solve the issue as extract-text uses a child compiler. I'll release a new version by the end of this week.
